variable "db_identifier" {}
variable "db_instance_class" {}
variable "db_allocated_storage" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_security_group_id" {}
variable "db_subnet_group" {}
variable "vpc_id" {}
