name: AWS Deployment Workflow
on:
  - workflow_dispatch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-aws-resources:
    runs-on: ubuntu-latest
    environment: webstore-deployment
    container:
      image: hashicorp/terraform:1.7.5
      options: --workdir /github/workspace
    env:
      TF_VAR_aws_region: "eu-central-1"
      TF_VAR_db_identifier: "webstore-pg"
      TF_VAR_db_instance_class: "db.t3.micro"
      TF_VAR_db_allocated_storage: "20"
      TF_VAR_vpc_id: "vpc-02b0cb05f448d2882"
      TF_VAR_instance_type: "t2.micro"
      TF_VAR_subnet_ids: '[ "subnet-0185a7f112cd61262", "subnet-045923f8e41d39e3e", "subnet-02a1320e66b8555de" ]'
      TF_VAR_db_name: ${{ secrets.POSTGRES_DB }}
      TF_VAR_db_username: ${{ secrets.POSTGRES_USER }}
      TF_VAR_db_password: ${{ secrets.POSTGRES_PWD }}
      TF_VAR_db_security_group_id: ${{ secrets.RDS_SG }}
      TF_VAR_db_subnet_group: ${{ secrets.PRIVATE_SUBNET_GROUP }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::912405945745:role/GithubDeployer
          role-session-name: ${{ github.actor }}@${{ github.run_id }}
          aws-region: eu-central-1
  
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/
