name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - version2
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: grocery_webstore
          IMAGE_TAG: 1.0
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/$username/$IMAGE_NAME:$IMAGE_TAG
              docker push ghcr.io/$username/$IMAGE_NAME:$IMAGE_TAG
